### ISSUE TITLE
another work

### ISSUE THREAD

**Issue by 1061700625** [chicleee/Image-Matching-Paper-List#3]
There is a research trend to fuse traditional features and deep features, like Key.Net and this one. But they have different stages of fusion:

Image Matching and Localization Based on Fusion of Handcrafted and Deep Features[[IEEE Sensors Journal 2023](https://ieeexplore.ieee.org/document/10225672)][[DeFusion](https://github.com/songxf1024/DeFusion)]

**Comment by chicleee** [comment]
Updated :)

**Comment by 1061700625** [comment]
thank you very much! (*^▽^*)
