### ISSUE TITLE
add image matching challenge 2024 link

### ISSUE THREAD

**Issue by c-schicho** [chicleee/Image-Matching-Paper-List#4]
During some research for the 2024 image matching challenge, I came across this repository. It's an awesome summary!

However, I saw that this year's challenge is not listed under "Challenges and workshops", so I just leave this issue here, as kind of reminder :smile_cat: 

this would be the link: https://www.kaggle.com/competitions/image-matching-challenge-2024

Thanks for your great work!

**Comment by chicleee** [comment]
Updated. Looking forward to seeing excellent works at this year's challenge. :smile:
